apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpcdemo-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "grpcdemo-server.name" . }}
    helm.sh/chart: {{ include "grpcdemo-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "grpcdemo-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "grpcdemo-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "grpcdemo-server.name" . }}
    helm.sh/chart: {{ include "grpcdemo-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    monitoring: promop # this must match prometheus.prometheusSpec.serviceMonitorSelector in prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grpcdemo-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      interval: 15s