apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grpcdemo-client.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "grpcdemo-client.name" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grpcdemo-client.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  template:
    metadata:
      {{- if .Values.enableLinkerdInjection }}
      annotations:
        linkerd.io/inject: enabled
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "grpcdemo-client.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          args:
            - "-wait_nanos={{ .Values.application.waitNanos }}"
            {{- if .Values.application.useGrpcStreaming }}
            - "-use_streaming"]
            {{- end }}
          env:
            - name: SERVER_ADDR
              value: "{{ .Values.grpcserver.addr }}:{{ .Values.grpcserver.port }}"
          ports:
            - name: metrics
              containerPort: 2112
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
